/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as EditorIndexImport } from './routes/editor/index'
import { Route as EditorSlugImport } from './routes/editor/$slug'
import { Route as ArticleSlugImport } from './routes/article.$slug'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username/route'
import { Route as ProfileUsernameIndexImport } from './routes/profile/$username/index'
import { Route as ProfileUsernameFavoritesImport } from './routes/profile/$username/favorites'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EditorIndexRoute = EditorIndexImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => rootRoute,
} as any)

const EditorSlugRoute = EditorSlugImport.update({
  id: '/editor/$slug',
  path: '/editor/$slug',
  getParentRoute: () => rootRoute,
} as any)

const ArticleSlugRoute = ArticleSlugImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRoute,
} as any)

const ProfileUsernameRouteRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRoute,
} as any)

const ProfileUsernameIndexRoute = ProfileUsernameIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)

const ProfileUsernameFavoritesRoute = ProfileUsernameFavoritesImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRoute
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugImport
      parentRoute: typeof rootRoute
    }
    '/editor/$slug': {
      id: '/editor/$slug'
      path: '/editor/$slug'
      fullPath: '/editor/$slug'
      preLoaderRoute: typeof EditorSlugImport
      parentRoute: typeof rootRoute
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/$username/favorites': {
      id: '/profile/$username/favorites'
      path: '/favorites'
      fullPath: '/profile/$username/favorites'
      preLoaderRoute: typeof ProfileUsernameFavoritesImport
      parentRoute: typeof ProfileUsernameRouteImport
    }
    '/profile/$username/': {
      id: '/profile/$username/'
      path: '/'
      fullPath: '/profile/$username/'
      preLoaderRoute: typeof ProfileUsernameIndexImport
      parentRoute: typeof ProfileUsernameRouteImport
    }
  }
}

// Create and export the route tree

interface ProfileUsernameRouteRouteChildren {
  ProfileUsernameFavoritesRoute: typeof ProfileUsernameFavoritesRoute
  ProfileUsernameIndexRoute: typeof ProfileUsernameIndexRoute
}

const ProfileUsernameRouteRouteChildren: ProfileUsernameRouteRouteChildren = {
  ProfileUsernameFavoritesRoute: ProfileUsernameFavoritesRoute,
  ProfileUsernameIndexRoute: ProfileUsernameIndexRoute,
}

const ProfileUsernameRouteRouteWithChildren =
  ProfileUsernameRouteRoute._addFileChildren(ProfileUsernameRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/profile/$username': typeof ProfileUsernameRouteRouteWithChildren
  '/article/$slug': typeof ArticleSlugRoute
  '/editor/$slug': typeof EditorSlugRoute
  '/editor': typeof EditorIndexRoute
  '/profile/$username/favorites': typeof ProfileUsernameFavoritesRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/editor/$slug': typeof EditorSlugRoute
  '/editor': typeof EditorIndexRoute
  '/profile/$username/favorites': typeof ProfileUsernameFavoritesRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/profile/$username': typeof ProfileUsernameRouteRouteWithChildren
  '/article/$slug': typeof ArticleSlugRoute
  '/editor/$slug': typeof EditorSlugRoute
  '/editor/': typeof EditorIndexRoute
  '/profile/$username/favorites': typeof ProfileUsernameFavoritesRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/profile/$username'
    | '/article/$slug'
    | '/editor/$slug'
    | '/editor'
    | '/profile/$username/favorites'
    | '/profile/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/article/$slug'
    | '/editor/$slug'
    | '/editor'
    | '/profile/$username/favorites'
    | '/profile/$username'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/profile/$username'
    | '/article/$slug'
    | '/editor/$slug'
    | '/editor/'
    | '/profile/$username/favorites'
    | '/profile/$username/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  ProfileUsernameRouteRoute: typeof ProfileUsernameRouteRouteWithChildren
  ArticleSlugRoute: typeof ArticleSlugRoute
  EditorSlugRoute: typeof EditorSlugRoute
  EditorIndexRoute: typeof EditorIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  ProfileUsernameRouteRoute: ProfileUsernameRouteRouteWithChildren,
  ArticleSlugRoute: ArticleSlugRoute,
  EditorSlugRoute: EditorSlugRoute,
  EditorIndexRoute: EditorIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/register",
        "/settings",
        "/profile/$username",
        "/article/$slug",
        "/editor/$slug",
        "/editor/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/profile/$username": {
      "filePath": "profile/$username/route.tsx",
      "children": [
        "/profile/$username/favorites",
        "/profile/$username/"
      ]
    },
    "/article/$slug": {
      "filePath": "article.$slug.tsx"
    },
    "/editor/$slug": {
      "filePath": "editor/$slug.tsx"
    },
    "/editor/": {
      "filePath": "editor/index.tsx"
    },
    "/profile/$username/favorites": {
      "filePath": "profile/$username/favorites.tsx",
      "parent": "/profile/$username"
    },
    "/profile/$username/": {
      "filePath": "profile/$username/index.tsx",
      "parent": "/profile/$username"
    }
  }
}
ROUTE_MANIFEST_END */
